@baseUrl = http://localhost:3003/api

### Get all blogs
GET {{baseUrl}}/blogs

### Create new blog
POST {{baseUrl}}/blogs
Content-Type: application/json
{
  "title": "Awesome Blog",
  "authorId": "668812eaa50070c4f3cd2649",
  "url": "http://example.com/awesome-blog",
  "likes": 100
}

### Update blog
PUT {{baseUrl}}/blogs/668812eaa50070c4f3cd2649
Content-Type: application/json
{
  "title": "Update",
  "author": "One more",
  "url": "Another",
  "likes": 10000
}
### Delete blog
DELETE {{baseUrl}}/blogs/668a51269421cdc10323d1a7

### Add user
POST {{baseUrl}}/users
Content-Type: application/json
{
  "username": "Nemmie",
  "password": "pass",
  "name": "Nem"
}

### Get all users
GET {{baseUrl}}/users

### Delete user
DELETE {{baseUrl}}/users/66884b1feb6ff358eab82ce9
