@baseUrl = http://localhost:3003/api

### Get all blogs

GET {{baseUrl}}/blogs

### Create new blog

POST {{baseUrl}}/blogs
Content-Type: application/json
{
  "title": "Awesome Blog 2",
  "author": "Pem",
  "url": "http://example.com/awesome-blog",
  "likes": 100
}

### Update blog

PUT {{baseUrl}}/blogs/668812eaa50070c4f3cd2649
Content-Type: application/json
{
  "title": "Update",
  "author": "One more",
  "url": "Another",
  "likes": 10000
}

### Add user

POST {{baseUrl}}/users
Content-Type: application/json
{
  "username": "Nemmie",
  "password": "pass",
  "name": "Nem"
}

### Get all users

GET {{baseUrl}}/users
